### ISSUE TITLE
Unable to push commits

### ISSUE THREAD

**Issue by Hicksdesign** [rachelandrew/futuresimplesteps#10]
Instead, here's my book info!

---

author-name: "Jon Hicks "
author-name-short: "Jon"
author-website: "https://hicksdesign.co.uk"
author-twitter: "hicksdesign"
book-title: "The Icon Handbook"
book-slug: "icon-handbook"
## book-url: "https://gumroad.com/l/YPdSl"

_Have you ever needed to create an icon, and not known where to start?_

How do you go about crafting the right message, the tone, the line work and getting it to work in the environment it's supposed to; be it mobile, operating system, or browser?

The Icon Handbook is the only resource that guides you through the complete process of designing icons - from deciding on the correct metaphor, drawing clear & understandable symbols and implementing in your websites and apps. 

This book begins at the point when you need to create your own icons. Its purpose is to guide relatively inexperienced designers through an icon design workflow, starting with favicons and working up to application icons, as well as inspiring and providing a reference point for existing icon designers. The aim is not to improve proficiency in particular applications but, rather, to show you how to create icons with the common toolset found in most of them, so you can be more versatile.

The download contains the book in ePub, PDF and Mobi formats.

**Comment by maban** [comment]
It's up!

**Comment by Hicksdesign** [comment]
I'm not worthy! \o/
